### ISSUE TITLE
Add option to download create YAML

### ISSUE THREAD

**Issue by aparcar** [aparcar/devices#4]
The form should offer two buttons, one to "show" the created YAML and one to download it as `<device_id>.yml`.

**Comment by Aditi-1400** [comment]
Okay, so the current implementation is this: (When we click on save: the yaml file is downloaded)
![Screenshot from 2021-06-28 15-04-54](https://user-images.githubusercontent.com/62544124/123614884-616db700-d822-11eb-9adf-2fa696f00b41.png)

And I assume you're suggesting that we need to remove the save button from the modal, and add it at the end of the form something like:
![Screenshot from 2021-06-28 15-20-14](https://user-images.githubusercontent.com/62544124/123616918-5f0c5c80-d824-11eb-82d7-676827825efd.png)

**Comment by aparcar** [comment]
Yea Looks good
